### ISSUE TITLE
Crash with ffmpeg 2.4 on GNU/Linux

### ISSUE THREAD

**Issue by mdevlamynck** [GabuEx/my-little-investigations#33]
I was trying to package the 1.0.8 version for ArchLinux when I saw that the game crashed when loading the intro video. It happens in [src/ResourceLoader.cpp ligne 271](https://github.com/GabuEx/my-little-investigations/blob/91ed961c090bfb2c8c2c3674fdad344cd99b07f2/src/ResourceLoader.cpp#L271) :
`pFormatContext->iformat = av_probe_input_format(&probeData, 1);`

because `pFormatContext` is null. And It's null because `avformat_alloc_context() ` returns null.

It only happens with ffmpeg 2.4 for me. With ffmpeg 2.3 it runs well.

Anyone else having this issue ?

It seems to be a ffmpeg problem so I'll probably report it to ffmpeg devs if confirmed.

**Comment by mdevlamynck** [comment]
Me too, I updated the ArchLinux package and I'm using the -O2 again. Thanks !

**Comment by GabuEx** [comment]
Sweet, glad to hear this sounds like it's fixed. :)
